#!/usr/bin/env python
import os
import sys
import urllib2
import re
from flask import Flask, render_template, request, url_for
from flask import json

from Google import index as gplusIndex

app = Flask(__name__)
app.debug = True

g_plus_index = None

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/health')
def monitor():
    return "1"

@app.route('/env')
def get_env():
    environ = request.environ
    response_body = ['%s: %s' % (key, value)
                    for key, value in sorted(environ.items())]
    response_body = '\n'.join(response_body)
    return response_body

@app.route('/openshift')
def show_openshift():
	return render_template('openshift.html')

@app.route('/suggestions', methods = ['POST', 'GET'])
def get_suggestion():
    global g_plus_index
    # Get query terms from request
    terms = request.values['term']

    # Call API provided from backend module which gives suggestion
    # suggestion
    suggest = []
    if g_plus_index:
        sug_dict = g_plus_index.queryCompletion(terms)

        #suggest = [{"id":"Botaurus stellaris","label":"Great Bittern","value":"Great Bittern"},{"id":"Ixobrychus minutus","label":"Little Bittern","value":"Little Bittern"},{"id":"Ciconia ciconia","label":"White Stork","value":"White Stork"},{"id":"Netta rufina","label":"Red-crested Pochard","value":"Red-crested Pochard"},{"id":"Milvus milvus","label":"Red Kite","value":"Red Kite"},{"id":"Porzana porzana","label":"Spotted Crake","value":"Spotted Crake"},{"id":"Sterna sandvicensis","label":"Sandwich Tern","value":"Sandwich Tern"},{"id":"Sterna hirundo","label":"Common Tern","value":"Common Tern"},{"id":"Sterna paradisaea","label":"Arctic Tern","value":"Arctic Tern"},{"id":"Sternula albifrons","label":"Little Tern","value":"Little Tern"},{"id":"Chlidonias niger","label":"Black Tern","value":"Black Tern"},{"id":"Galerida cristata","label":"Crested Lark","value":"Crested Lark"}]
        suggest = sug_dict.get('suggestions', [])

    # Call API provided from backend module which gives suggestion friends
    # 
    #friends = [{"jid":"dincoco@gmail.com", "name":"Tony"},
    #           {"jid":"dx88968@gmail.com", "name":"Xu Xun"},
    #           {"jid":"eastflag163@gmail.com", "name":"Li Pengfei"}
    #          ]
    friends = []
    if g_plus_index:
        friends = g_plus_index.getHelperList(terms)

    rv = {'suggestions' : suggest, 'friends' : friends}
    # Return JSON data
    return json.JSONEncoder().encode(rv)

@app.route('/friends', methods = ['POST', 'GET'])
def get_friends():
    # Get query terms from request
    terms = request.values['term']

    # Call API provided from backend module which gives suggestion friends
    # get_friends()
    friends = [{"jid":"dincoco@gmail.com", "name":"Tony"},
           {"jid":"dx88968@gmail.com", "name":"Xu Xun"},
           {"jid":"eastflag163@gmail.com", "name":"Li Pengfei"}
          ]

    # Return JSON data
    return json.JSONDecoder().encode(friends)

@app.route('/search', methods = ['POST', 'GET'])
def search_by_google():
    search_url = 'http://www.google.com/search?hl=en&q='
    search_url += request.values['term'];

    req = urllib2.Request(search_url)
    req.add_header('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:20.0) Gecko/20100101 Firefox/20.0')
    response = urllib2.urlopen(req)
    html = response.read()
    html = re.subn(r'<(script).*?</\1>(?s)', '', html)[0]
    return html

@app.route('/oauth2callback', methods = ['POST', 'GET'])
def oauth2_cb():
    global g_plus_index
    
    if 'error' in request.values.keys():
        return request.values['error']
    else:
        # Call Google Plus API to get Access Token
        #
        # Google Plus APIs
        g_plus_index = gplusIndex.dx_indexer(request.values['code'])
        return 'You Grant us to Access your Google Plus Information:%s.' % g_plus_index.getProgress()['Status']
    

#
# Below for testing only
#
if __name__ == '__main__':
	from wsgiref.simple_server import make_server
	httpd = make_server('localhost', 8051, application)
	# Wait for a single request, serve it and quit.
	httpd.handle_request()
