#!/usr/bin/env python
import os
import sys
from flask import Flask, render_template, request, url_for
from flask import json

app = Flask(__name__)

@app.route('/')
def index():
        return render_template('index.html')

@app.route('/health')
def monitor():
        return "1"

@app.route('/env')
def get_env():
        environ = request.environ
        response_body = ['%s: %s' % (key, value)
                    for key, value in sorted(environ.items())]
	response_body = '\n'.join(response_body)
	return response_body

@app.route('/openshift')
def show_openshift():
	return render_tempalte('openshift.html')

@app.route('/suggestions', methods = ['POST', 'GET'])
def get_suggestion():
        # Get query terms from request
        terms = request.values['term']

        # Call API provided from backend module which gives suggestion
        # get_suggestion()
        suggest = [{"id":"Botaurus stellaris","label":"Great Bittern","value":"Great Bittern"},{"id":"Ixobrychus minutus","label":"Little Bittern","value":"Little Bittern"},{"id":"Ciconia ciconia","label":"White Stork","value":"White Stork"},{"id":"Netta rufina","label":"Red-crested Pochard","value":"Red-crested Pochard"},{"id":"Milvus milvus","label":"Red Kite","value":"Red Kite"},{"id":"Porzana porzana","label":"Spotted Crake","value":"Spotted Crake"},{"id":"Sterna sandvicensis","label":"Sandwich Tern","value":"Sandwich Tern"},{"id":"Sterna hirundo","label":"Common Tern","value":"Common Tern"},{"id":"Sterna paradisaea","label":"Arctic Tern","value":"Arctic Tern"},{"id":"Sternula albifrons","label":"Little Tern","value":"Little Tern"},{"id":"Chlidonias niger","label":"Black Tern","value":"Black Tern"},{"id":"Galerida cristata","label":"Crested Lark","value":"Crested Lark"}]

        # Return JSON data
        return json.encode(suggest)

@app.route('/friends', methods = ['POST', 'GET'])
def get_friends():
        # Get query terms from request
        terms = request.values['term']

        # Call API provided from backend module which gives suggestion friends
        # get_friends()
        friends = [{"jid":"dincoco@gmail.com", "name":"Tony"},
                   {"jid":"dx88968@gmail.com", "name":"Xu Xun"},
                   {"jid":"eastflag163@gmail.com", "name":"Li Pengfei"}
                  ]

        # Return JSON data
        return json.encode(friends)

#
# Below for testing only
#
if __name__ == '__main__':
	from wsgiref.simple_server import make_server
	httpd = make_server('localhost', 8051, application)
	# Wait for a single request, serve it and quit.
	httpd.handle_request()
